### ISSUE TITLE
运营商选项

### ISSUE THREAD

**Issue by unlessyousay** [7Ji/auto-whu#1]
能否提供运营商（如电信，移动之类的）的选项呢？

**Comment by 7Ji** [comment]
https://github.com/7Ji/auto-whu-standard，普通linux发行版用的那个脚本可以直接跑在openwrt里，有做运营商区分

**Comment by 7Ji** [comment]
> 能否提供运营商（如电信，移动之类的）的选项呢？

@unlessyousay
https://github.com/7Ji/auto-whu-standard
普通linux发行版用的那个脚本可以直接跑在openwrt里，有做运营商区分
我已经毕业了所以懒得补充OpenWrt的这个版本了
把那边的curl post的那段代码直接替换到openwrt的这个脚本里就行了
